# Generated by Django 4.1.2 on 2022-10-21 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('davomat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='davomat',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='davomat.course')),
                ('pupils', models.ManyToManyField(to='davomat.pupil')),
            ],
        ),
        migrations.AddField(
            model_name='davomat',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='davomat.group'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(to='davomat.group'),
        ),
    ]
