# Generated by Django 4.1.1 on 2022-10-27 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('davomat', '0004_remove_group_teacher_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='davomat.coursetime'),
        ),
    ]
